// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCssbWNgsGa0LCwH3IqNOFtmgIxJkxOFbg',
    appId: '1:421889303134:web:8c61a81db90ca388c38acf',
    messagingSenderId: '421889303134',
    projectId: 'culturpass',
    authDomain: 'culturpass.firebaseapp.com',
    storageBucket: 'culturpass.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF--7i4-Py34KzswuIDWNyFERSbxj5UGY',
    appId: '1:421889303134:android:f0f1573834bc52e5c38acf',
    messagingSenderId: '421889303134',
    projectId: 'culturpass',
    storageBucket: 'culturpass.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYGDChQdGZ8SezDKeWPVVlGK_2_EoNgKM',
    appId: '1:421889303134:ios:cd270909969970c5c38acf',
    messagingSenderId: '421889303134',
    projectId: 'culturpass',
    storageBucket: 'culturpass.firebasestorage.app',
    iosBundleId: 'com.example.suiviBudget',
  );
}
